language: c cpp python

python:
  - "3.6"

# HTSLib, GSL and Autotools needed
before_install:
  - sudo add-apt-repository ppa:ondrej/autotools -y
  - sudo add-apt-repository ppa:debian-med/ppa -y
  - sudo add-apt-repository ppa:dluxen/boost -y
  - sudo apt-get update -qq
  - sudo apt-get install -y --allow-unauthenticated libhts-dev libboost-random1.67-dev gsl-bin libgsl0-dev autoconf automake pkg-config m4
  - source ~/virtualenv/python3.6/bin/activate

compiler:
  - gcc

before_script: autoreconf -vif
script: ./configure && make -j1 distcheck
